SuperAnimalConversionTables:
Task: mouse_tracking
TrainingFraction:
- 0.95
alphavalue: 0.4
batch_size: 8
bodyparts:
- Nose
- Tail
- FL_gen
- FR_gen
- BL_gen
- BR_gen
colormap: rainbow
corner2move2:
- 50
- 50
cropping: true
date: May19
default_augmenter: default
default_net_type: resnet_50
detector_batch_size: 1
detector_snapshotindex: -1
dotsize: 3
engine: pytorch
identity:
iteration: 0
move2corner: true
multianimalproject: false
numframes2pick: 20
pcutoff: 0.6
project_path: /opt/app/dlcfilterpipeline
scorer: lake_lab
skeleton:
- - Nose
  - Tail
- - Nose
  - FL_gen
- - Tail
  - BL_gen
- - Nose
  - FR_gen
- - Tail
  - BR_gen
skeleton_color: yellow
snapshotindex: -1
start: 0
stop: 1
video_sets:
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240610_4132_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240610_4135_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240610_4141_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240610_4146_11.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240624_4132_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240624_4135_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20240624_4141_04.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250103_4355_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250103_4365_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250103_4373_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250103_4394_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250103_4396_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250114_4355_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250114_4365_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250114_4373_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250114_4394_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250114_4396_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250121_4355_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250121_4365_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250121_4373_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250121_4394_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250121_4396_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250428_4551_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250428_4556_01.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250506_4551_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250506_4556_02.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250513_4551_03.avi:
    crop: 0, 1280, 420, 720
  /Volumes/lake.s/Active/Shawn P/AAA. DEEPLABCUT/0_TRACKING_ONLY/20250513_4556_03.avi:
    crop: 0, 1280, 420, 720
x1: 0
x2: 1280
y1: 420
y2: 720
